version: '3.9'

networks:
    app-tier:

services:
  todos:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-tier
    depends_on:
      - pgsqldb
  pgsqldb:
    image: postgres:16
    ports:
      - "5432:5432"
    networks:
      - app-tier
    env_file:
      - .env
    environment:
      - POSTGRES_USER 
      - POSTGRES_PASSWORD 
      - POSTGRES_DB 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    